# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
    groups:
        # Specify a name for the group, which will be used in pull request titles
        # and branch names
        storybook-ecosystem:
            # Define patterns to include dependencies in the group (based on
            # dependency name)
            patterns:
                - 'storybook'
                - '@storybook/*'
                - '@types/storybook*'
        # Specify a name for the group, which will be used in pull request titles
        # and branch names
        modern-web-ecosystem:
            # Define patterns to include dependencies in the group (based on
            # dependency name)
            patterns:
                - '@open-wc/*'
                - '@web/*'
